//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blitzy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blitzy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always stay on top.
        /// </summary>
        public static string AlawysStayOnTop {
            get {
                return ResourceManager.GetString("AlawysStayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for confirmation before logging off.
        /// </summary>
        public static string AskForLogoffConfirmation {
            get {
                return ResourceManager.GetString("AskForLogoffConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for confirmation before restarting.
        /// </summary>
        public static string AskForRestartConfirmation {
            get {
                return ResourceManager.GetString("AskForRestartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for confirmation before shutting down.
        /// </summary>
        public static string AskForShutdownConfirmation {
            get {
                return ResourceManager.GetString("AskForShutdownConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string AutomaticallyCheckForUpdates {
            get {
                return ResourceManager.GetString("AutomaticallyCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzy.
        /// </summary>
        public static string Blitzy {
            get {
                return ResourceManager.GetString("Blitzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzy140.
        /// </summary>
        public static string Blitzy140 {
            get {
                return ResourceManager.GetString("Blitzy140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate a wide set of mathematical.
        /// </summary>
        public static string CalcyDescription {
            get {
                return ResourceManager.GetString("CalcyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close after command execution.
        /// </summary>
        public static string CloseAfterCommandExecution {
            get {
                return ResourceManager.GetString("CloseAfterCommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close on escape.
        /// </summary>
        public static string CloseOnEscape {
            get {
                return ResourceManager.GetString("CloseOnEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close when focus lost.
        /// </summary>
        public static string CloseWhenFocusLost {
            get {
                return ResourceManager.GetString("CloseWhenFocusLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation required.
        /// </summary>
        public static string ConfirmationRequired {
            get {
                return ResourceManager.GetString("ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this item?.
        /// </summary>
        public static string ConfirmDeleteItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to proceed with the selected operation?.
        /// </summary>
        public static string ConfirmOperation {
            get {
                return ResourceManager.GetString("ConfirmOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control a media player.
        /// </summary>
        public static string ControlMediaPlayer {
            get {
                return ResourceManager.GetString("ControlMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty expression.
        /// </summary>
        public static string EmptyExpression {
            get {
                return ResourceManager.GetString("EmptyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excludes.
        /// </summary>
        public static string Excludes {
            get {
                return ResourceManager.GetString("Excludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External plugins.
        /// </summary>
        public static string ExternalPlugins {
            get {
                return ResourceManager.GetString("ExternalPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string FolderDots {
            get {
                return ResourceManager.GetString("FolderDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import saved sessions.
        /// </summary>
        public static string ImportSavedSessions {
            get {
                return ResourceManager.GetString("ImportSavedSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Expression.
        /// </summary>
        public static string IncompleteExpression {
            get {
                return ResourceManager.GetString("IncompleteExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep input content.
        /// </summary>
        public static string KeppInputContent {
            get {
                return ResourceManager.GetString("KeppInputContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs off the currently logged in user.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a backup of shortcuts before parsing them.
        /// </summary>
        public static string MakeBackupOfShortcuts {
            get {
                return ResourceManager.GetString("MakeBackupOfShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals a media player it should move to the next item.
        /// </summary>
        public static string MedyNext {
            get {
                return ResourceManager.GetString("MedyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals a media player it should pause.
        /// </summary>
        public static string MedyPause {
            get {
                return ResourceManager.GetString("MedyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals a media player it should start playing.
        /// </summary>
        public static string MedyPlay {
            get {
                return ResourceManager.GetString("MedyPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals a media player it should move to the previous item.
        /// </summary>
        public static string MedyPrev {
            get {
                return ResourceManager.GetString("MedyPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases the volume.
        /// </summary>
        public static string MedyVoldn {
            get {
                return ResourceManager.GetString("MedyVoldn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the volume.
        /// </summary>
        public static string MedyVolup {
            get {
                return ResourceManager.GetString("MedyVolup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to your PuTTY.exe.
        /// </summary>
        public static string PathToPutty {
            get {
                return ResourceManager.GetString("PathToPutty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically rebuild catalog.
        /// </summary>
        public static string PeriodicallyRebuildCatalog {
            get {
                return ResourceManager.GetString("PeriodicallyRebuildCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putty.
        /// </summary>
        public static string Putty {
            get {
                return ResourceManager.GetString("Putty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Blitzy.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild the command catalog.
        /// </summary>
        public static string RebuildCatalog {
            get {
                return ResourceManager.GetString("RebuildCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild catalog on changed settings.
        /// </summary>
        public static string RebuildCatalogOnChangedSettings {
            get {
                return ResourceManager.GetString("RebuildCatalogOnChangedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        public static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset command execution count.
        /// </summary>
        public static string ResetCommand {
            get {
                return ResourceManager.GetString("ResetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the computer.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a command using the PowerShell.
        /// </summary>
        public static string ShellyDescription {
            get {
                return ResourceManager.GetString("ShellyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tray icon.
        /// </summary>
        public static string ShowTrayIcon {
            get {
                return ResourceManager.GetString("ShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts the computer down.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System plugins.
        /// </summary>
        public static string SystemPlugins {
            get {
                return ResourceManager.GetString("SystemPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownCommand.
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update catalog.
        /// </summary>
        public static string UpdateCatalog {
            get {
                return ResourceManager.GetString("UpdateCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} as a placeholder for the user input.
        /// </summary>
        public static string URLTooltipPlaceholder {
            get {
                return ResourceManager.GetString("URLTooltipPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check online for a updates.
        /// </summary>
        public static string VersionCheck {
            get {
                return ResourceManager.GetString("VersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weby.
        /// </summary>
        public static string Weby {
            get {
                return ResourceManager.GetString("Weby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winy.
        /// </summary>
        public static string Winy {
            get {
                return ResourceManager.GetString("Winy", resourceCulture);
            }
        }
    }
}
